### ISSUE TITLE
Getting error while executing step 2.

### ISSUE THREAD

**Issue by rvaishali23** [darolt/wsn#7]
I'm a newbie. I don't know much about this code. 
I'm using Python 3.7 in windows 10
While executing the code "python setup.py build_ext --inplace"
I got the following error:
cc/modified_pso.cc(146): error C7555: use of designated initializers requires at least '/std:c++latest'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

I installed mysql connector c  6.1 and copied it into program Files(x86).
I don't know any other ways. Can you help me please?

**Comment by kerennaomid** [comment]
hey, how did you fix this issue ?
